export const BIBLE_BOOKS = [
    // Old Testament
    { name: "Génesis", chapters: 50, testament: "Antiguo" },
    { name: "Éxodo", chapters: 40, testament: "Antiguo" },
    { name: "Levítico", chapters: 27, testament: "Antiguo" },
    { name: "Números", chapters: 36, testament: "Antiguo" },
    { name: "Deuteronomio", chapters: 34, testament: "Antiguo" },
    { name: "Josué", chapters: 24, testament: "Antiguo" },
    { name: "Jueces", chapters: 21, testament: "Antiguo" },
    { name: "Rut", chapters: 4, testament: "Antiguo" },
    { name: "1 Samuel", chapters: 31, testament: "Antiguo" },
    { name: "2 Samuel", chapters: 24, testament: "Antiguo" },
    { name: "1 Reyes", chapters: 22, testament: "Antiguo" },
    { name: "2 Reyes", chapters: 25, testament: "Antiguo" },
    { name: "1 Crónicas", chapters: 29, testament: "Antiguo" },
    { name: "2 Crónicas", chapters: 36, testament: "Antiguo" },
    { name: "Esdras", chapters: 10, testament: "Antiguo" },
    { name: "Nehemías", chapters: 13, testament: "Antiguo" },
    { name: "Ester", chapters: 10, testament: "Antiguo" },
    { name: "Job", chapters: 42, testament: "Antiguo" },
    { name: "Salmos", chapters: 150, testament: "Antiguo" },
    { name: "Proverbios", chapters: 31, testament: "Antiguo" },
    { name: "Eclesiastés", chapters: 12, testament: "Antiguo" },
    { name: "Cantares", chapters: 8, testament: "Antiguo" },
    { name: "Isaías", chapters: 66, testament: "Antiguo" },
    { name: "Jeremías", chapters: 52, testament: "Antiguo" },
    { name: "Lamentaciones", chapters: 5, testament: "Antiguo" },
    { name: "Ezequiel", chapters: 48, testament: "Antiguo" },
    { name: "Daniel", chapters: 12, testament: "Antiguo" },
    { name: "Oseas", chapters: 14, testament: "Antiguo" },
    { name: "Joel", chapters: 3, testament: "Antiguo" },
    { name: "Amós", chapters: 9, testament: "Antiguo" },
    { name: "Abdías", chapters: 1, testament: "Antiguo" },
    { name: "Jonás", chapters: 4, testament: "Antiguo" },
    { name: "Miqueas", chapters: 7, testament: "Antiguo" },
    { name: "Nahúm", chapters: 3, testament: "Antiguo" },
    { name: "Habacuc", chapters: 3, testament: "Antiguo" },
    { name: "Sofonías", chapters: 3, testament: "Antiguo" },
    { name: "Hageo", chapters: 2, testament: "Antiguo" },
    { name: "Zacarías", chapters: 14, testament: "Antiguo" },
    { name: "Malaquías", chapters: 4, testament: "Antiguo" },

    // New Testament
    { name: "Mateo", chapters: 28, testament: "Nuevo" },
    { name: "Marcos", chapters: 16, testament: "Nuevo" },
    { name: "Lucas", chapters: 24, testament: "Nuevo" },
    { name: "Juan", chapters: 21, testament: "Nuevo" },
    { name: "Hechos", chapters: 28, testament: "Nuevo" },
    { name: "Romanos", chapters: 16, testament: "Nuevo" },
    { name: "1 Corintios", chapters: 16, testament: "Nuevo" },
    { name: "2 Corintios", chapters: 13, testament: "Nuevo" },
    { name: "Gálatas", chapters: 6, testament: "Nuevo" },
    { name: "Efesios", chapters: 6, testament: "Nuevo" },
    { name: "Filipenses", chapters: 4, testament: "Nuevo" },
    { name: "Colosenses", chapters: 4, testament: "Nuevo" },
    { name: "1 Tesalonicenses", chapters: 5, testament: "Nuevo" },
    { name: "2 Tesalonicenses", chapters: 3, testament: "Nuevo" },
    { name: "1 Timoteo", chapters: 6, testament: "Nuevo" },
    { name: "2 Timoteo", chapters: 4, testament: "Nuevo" },
    { name: "Tito", chapters: 3, testament: "Nuevo" },
    { name: "Filemón", chapters: 1, testament: "Nuevo" },
    { name: "Hebreos", chapters: 13, testament: "Nuevo" },
    { name: "Santiago", chapters: 5, testament: "Nuevo" },
    { name: "1 Pedro", chapters: 5, testament: "Nuevo" },
    { name: "2 Pedro", chapters: 3, testament: "Nuevo" },
    { name: "1 Juan", chapters: 5, testament: "Nuevo" },
    { name: "2 Juan", chapters: 1, testament: "Nuevo" },
    { name: "3 Juan", chapters: 1, testament: "Nuevo" },
    { name: "Judas", chapters: 1, testament: "Nuevo" },
    { name: "Apocalipsis", chapters: 22, testament: "Nuevo" },
];
