
const bookMapping = {
    "gn": { name: "Génesis", testament: "Old" },
    "ex": { name: "Éxodo", testament: "Old" },
    "lv": { name: "Levítico", testament: "Old" },
    "nm": { name: "Números", testament: "Old" },
    "dt": { name: "Deuteronomio", testament: "Old" },
    "js": { name: "Josué", testament: "Old" },
    "jud": { name: "Jueces", testament: "Old" },
    "rt": { name: "Rut", testament: "Old" },
    "1sm": { name: "1 Samuel", testament: "Old" },
    "2sm": { name: "2 Samuel", testament: "Old" },
    "1kgs": { name: "1 Reyes", testament: "Old" },
    "2kgs": { name: "2 Reyes", testament: "Old" },
    "1ch": { name: "1 Crónicas", testament: "Old" },
    "2ch": { name: "2 Crónicas", testament: "Old" },
    "ezr": { name: "Esdras", testament: "Old" },
    "ne": { name: "Nehemías", testament: "Old" },
    "et": { name: "Ester", testament: "Old" },
    "job": { name: "Job", testament: "Old" },
    "ps": { name: "Salmos", testament: "Old" },
    "prv": { name: "Proverbios", testament: "Old" },
    "ec": { name: "Eclesiastés", testament: "Old" },
    "so": { name: "Cantares", testament: "Old" },
    "is": { name: "Isaías", testament: "Old" },
    "jr": { name: "Jeremías", testament: "Old" },
    "lm": { name: "Lamentaciones", testament: "Old" },
    "ez": { name: "Ezequiel", testament: "Old" },
    "dn": { name: "Daniel", testament: "Old" },
    "ho": { name: "Oseas", testament: "Old" },
    "jl": { name: "Joel", testament: "Old" },
    "am": { name: "Amós", testament: "Old" },
    "ob": { name: "Abdías", testament: "Old" },
    "jn": { name: "Jonás", testament: "Old" },
    "mi": { name: "Miqueas", testament: "Old" },
    "na": { name: "Nahúm", testament: "Old" },
    "hk": { name: "Habacuc", testament: "Old" },
    "zp": { name: "Sofonías", testament: "Old" },
    "hg": { name: "Hageo", testament: "Old" },
    "zc": { name: "Zacarías", testament: "Old" },
    "ml": { name: "Malaquías", testament: "Old" },
    "mt": { name: "Mateo", testament: "New" },
    "mk": { name: "Marcos", testament: "New" },
    "lk": { name: "Lucas", testament: "New" },
    "jo": { name: "Juan", testament: "New" },
    "act": { name: "Hechos", testament: "New" },
    "rm": { name: "Romanos", testament: "New" },
    "1co": { name: "1 Corintios", testament: "New" },
    "2co": { name: "2 Corintios", testament: "New" },
    "gl": { name: "Gálatas", testament: "New" },
    "eph": { name: "Efesios", testament: "New" },
    "ph": { name: "Filipenses", testament: "New" },
    "cl": { name: "Colosenses", testament: "New" },
    "1ts": { name: "1 Tesalonicenses", testament: "New" },
    "2ts": { name: "2 Tesalonicenses", testament: "New" },
    "1tm": { name: "1 Timoteo", testament: "New" },
    "2tm": { name: "2 Timoteo", testament: "New" },
    "tt": { name: "Tito", testament: "New" },
    "phm": { name: "Filemón", testament: "New" },
    "hb": { name: "Hebreos", testament: "New" },
    "jm": { name: "Santiago", testament: "New" },
    "1pe": { name: "1 Pedro", testament: "New" },
    "2pe": { name: "2 Pedro", testament: "New" },
    "1jo": { name: "1 Juan", testament: "New" },
    "2jo": { name: "2 Juan", testament: "New" },
    "3jo": { name: "3 Juan", testament: "New" },
    "jd": { name: "Judas", testament: "New" },
    "re": { name: "Apocalipsis", testament: "New" }
};

module.exports = { bookMapping };
