INSERT INTO scriptures (testament, book_name, chapter, verse_number, content, visual_theme) VALUES
('New', 'Apocalipsis', 18, 7, 'Cuanto ella se ha glorificado, y ha estado en deleites, tanto dadle de tormento y llanto; porque dice en su corazón: Yo estoy sentada reina, y no soy viuda, y no veré llanto.', 'fire'),
('New', 'Apocalipsis', 18, 8, 'Por lo cual en un día vendrán sus plagas, muerte, llanto y hambre, y será quemada con fuego; porque el Señor Dios es fuerte, que la juzgará.', 'fire'),
('New', 'Apocalipsis', 18, 9, 'Y llorarán y se lamentarán sobre ella los reyes de la tierra, los cuales han fornicado con ella y han vivido en deleites, cuando ellos vieren el humo de su incendio,', 'fire'),
('New', 'Apocalipsis', 18, 10, 'Estando lejos por el temor de su tormento, diciendo: ¡Ay, ay, de aquella gran ciudad de Babilonia, aquella fuerte ciudad; porque en una hora vino tu juicio!', 'fire'),
('New', 'Apocalipsis', 18, 11, 'Y los mercaderes de la tierra lloran y se lamentan sobre ella, porque ninguno compra más sus mercaderías:', 'fire'),
('New', 'Apocalipsis', 18, 12, 'Mercadería de oro, y de plata, y de piedras preciosas, y de margaritas, y de lino fino, y de escarlata, y de seda, y de grana, y de toda madera olorosa, y de todo vaso de marfil, y de todo vaso de madera preciosa, y de cobre, y de hierro, y de mármol;', 'fire'),
('New', 'Apocalipsis', 18, 13, 'Y canela, y olores, y ungüentos, y de incienso, y de vino, y de aceite; y flor de harina y trigo, y de bestias, y de ovejas; y de caballos, y de carros, y de siervos, y de almas de hombres.', 'fire'),
('New', 'Apocalipsis', 18, 14, 'Y los frutos del deseo de tu alma se apartaron de ti; y todas las cosas gruesas y excelentes te han faltado, y nunca más las hallarás.', 'fire'),
('New', 'Apocalipsis', 18, 15, 'Los mercaderes de estas cosas, que se han enriquecido, se pondrán lejos de ella por el temor de su tormento, llorando y lamentando,', 'fire'),
('New', 'Apocalipsis', 18, 16, 'Y diciendo: ¡Ay, ay, aquella gran ciudad, que estaba vestida de lino fino, y de escarlata, y de grana, y estaba dorada con oro, y adornada de piedras preciosas y de perlas!', 'fire'),
('New', 'Apocalipsis', 18, 17, 'Porque en una hora han sido desoladas tantas riquezas. Y todo patrón, y todos los que viajan en naves, y marineros, y todos los que trabajan en el mar, se estuvieron lejos;', 'fire'),
('New', 'Apocalipsis', 18, 18, 'Y viendo el humo de su incendio, dieron voces, diciendo: ¿Qué ciudad era semejante á esta gran ciudad?', 'fire'),
('New', 'Apocalipsis', 18, 19, 'Y echaron polvo sobre sus cabezas; y dieron voces, llorando y lamentando, diciendo: ¡Ay, ay, de aquella gran ciudad, en la cual todos los que tenían navíos en la mar se habían enriquecido de sus riquezas; que en una hora ha sido desolada!', 'fire'),
('New', 'Apocalipsis', 18, 20, 'Alégrate sobre ella, cielo, y vosotros, santos, apóstoles, y profetas; porque Dios ha vengado vuestra causa en ella.', 'fire'),
('New', 'Apocalipsis', 18, 21, 'Y un ángel fuerte tomó una piedra como una grande piedra de molino, y la echó en la mar, diciendo: Con tanto ímpetu será derribada Babilonia, aquella grande ciudad, y nunca jamás será hallada.', 'fire'),
('New', 'Apocalipsis', 18, 22, 'Y voz de tañedores de arpas, y de músicos, y de tañedores de flautas y de trompetas, no será más oída en ti; y todo artífice de cualquier oficio, no será más hallado en ti; y el sonido de muela no será más en ti oído:', 'fire'),
('New', 'Apocalipsis', 18, 23, 'Y luz de antorcha no alumbrará más en ti; y voz de esposo ni de esposa no será más en ti oída; porque tus mercaderes eran los magnates de la tierra; porque en tus hechicerías todas las gentes han errado.', 'fire'),
('New', 'Apocalipsis', 18, 24, 'Y en ella fué hallada la sangre de los profetas y de los santos, y de todos los que han sido muertos en la tierra.', 'fire'),
('New', 'Apocalipsis', 19, 1, 'DESPUÉS de estas cosas oí una gran voz de gran compañía en el cielo, que decía: Aleluya: Salvación y honra y gloria y potencia al Señor Dios nuestro', 'fire'),
('New', 'Apocalipsis', 19, 2, 'Porque sus juicios son verdaderos y justos; porque él ha juzgado á la grande ramera, que ha corrompido la tierra con su fornicación, y ha vengado la sangre de sus siervos de la mano de ella.', 'fire'),
('New', 'Apocalipsis', 19, 3, 'Y otra vez dijeron: Aleluya. Y su humo subió para siempre jamás.', 'fire'),
('New', 'Apocalipsis', 19, 4, 'Y los veinticuatro ancianos y los cuatro animales se postraron en tierra, y adoraron á Dios que estaba sentado sobre el trono, diciendo: Amén: Aleluya.', 'fire'),
('New', 'Apocalipsis', 19, 5, 'Y salió una voz del trono, que decía: Load á nuestro Dios todos sus siervos, y los que le teméis, así pequeños como grandes.', 'fire'),
('New', 'Apocalipsis', 19, 6, 'Y oí como la voz de una grande compañía, y como el ruido de muchas aguas, y como la voz de grandes truenos, que decía: Aleluya: porque reinó el Señor nuestro Dios Todopoderoso.', 'fire'),
('New', 'Apocalipsis', 19, 7, 'Gocémonos y alegrémonos y démosle gloria; porque son venidas las bodas del Cordero, y su esposa se ha aparejado.', 'fire'),
('New', 'Apocalipsis', 19, 8, 'Y le fué dado que se vista de lino fino, limpio y brillante: porque el lino fino son las justificaciones de los santos.', 'fire'),
('New', 'Apocalipsis', 19, 9, 'Y él me dice: Escribe: Bienaventurados los que son llamados á la cena del Cordero. Y me dijo: Estas palabras de Dios son verdaderas.', 'fire'),
('New', 'Apocalipsis', 19, 10, 'Y yo me eché á sus pies para adorarle. Y él me dijo: Mira que no lo hagas: yo soy siervo contigo, y con tus hermanos que tienen el testimonio de Jesús: adora á Dios; porque el testimonio de Jesús es el espíritu de la profecía.', 'fire'),
('New', 'Apocalipsis', 19, 11, 'Y vi el cielo abierto; y he aquí un caballo blanco, y el que estaba sentado sobre él, era llamado Fiel y Verdadero, el cual con justicia juzga y pelea.', 'fire'),
('New', 'Apocalipsis', 19, 12, 'Y sus ojos eran como llama de fuego, y había en su cabeza muchas diademas; y tenía un nombre escrito que ninguno entendía sino él mismo.', 'fire'),
('New', 'Apocalipsis', 19, 13, 'Y estaba vestido de una ropa teñida en sangre: y su nombre es llamado EL VERBO DE DIOS.', 'fire'),
('New', 'Apocalipsis', 19, 14, 'Y los ejércitos que están en el cielo le seguían en caballos blancos, vestidos de lino finísimo, blanco y limpio.', 'fire'),
('New', 'Apocalipsis', 19, 15, 'Y de su boca sale una espada aguda, para herir con ella las gentes: y él los regirá con vara de hierro; y él pisa el lagar del vino del furor, y de la ira del Dios Todopoderoso.', 'fire'),
('New', 'Apocalipsis', 19, 16, 'Y en su vestidura y en su muslo tiene escrito este nombre: REY DE REYES Y SEñOR DE SEñORES.', 'fire'),
('New', 'Apocalipsis', 19, 17, 'Y vi un ángel que estaba en el sol, y clamó con gran voz, diciendo á todas las aves que volaban por medio del cielo: Venid, y congregaos á la cena del gran Dios,', 'fire'),
('New', 'Apocalipsis', 19, 18, 'Para que comáis carnes de reyes, y de capitanes, y carnes de fuertes, y carnes de caballos, y de los que están sentados sobre ellos; y carnes de todos, libres y siervos, de pequeños y de grandes', 'fire'),
('New', 'Apocalipsis', 19, 19, 'Y vi la bestia, y los reyes de la tierra y sus ejércitos, congregados para hacer guerra contra el que estaba sentado sobre el caballo, y contra su ejército.', 'fire'),
('New', 'Apocalipsis', 19, 20, 'Y la bestia fué presa, y con ella el falso profeta que había hecho las señales delante de ella, con las cuales había engañado á los que tomaron la señal de la bestia, y habían adorado su imagen. Estos dos fueron lanzados vivos dentro de un lago de fuego ardiendo en azufre.', 'fire'),
('New', 'Apocalipsis', 19, 21, 'Y los otros fueron muertos con la espada que salía de la boca del que estaba sentado sobre el caballo, y todas las aves fueron hartas de las carnes de ellos.', 'fire'),
('New', 'Apocalipsis', 20, 1, 'Y VI un ángel descender del cielo, que tenía la llave del abismo, y una grande cadena en su mano.', 'fire'),
('New', 'Apocalipsis', 20, 2, 'Y prendió al dragón, aquella serpiente antigua, que es el Diablo y Satanás, y le ató por mil años;', 'fire'),
('New', 'Apocalipsis', 20, 3, 'Y arrojólo al abismo, y le encerró, y selló sobre él, porque no engañe más á las naciones, hasta que mil años sean cumplidos: y después de esto es necesario que sea desatado un poco de tiempo.', 'fire'),
('New', 'Apocalipsis', 20, 4, 'Y vi tronos, y se sentaron sobre ellos, y les fué dado juicio; y vi las almas de los degollados por el testimonio de Jesús, y por la palabra de Dios, y que no habían adorado la bestia, ni á su imagen, y que no recibieron la señal en sus frentes, ni en sus manos, y vivieron y reinaron con Cristo mil años.', 'fire'),
('New', 'Apocalipsis', 20, 5, 'Mas los otros muertos no tornaron á vivir hasta que sean cumplidos mil años. Esta es la primera resurrección.', 'fire'),
('New', 'Apocalipsis', 20, 6, 'Bienaventurado y santo el que tiene parte en la primera resurrección; la segunda muerte no tiene potestad en éstos; antes serán sacerdotes de Dios y de Cristo, y reinarán con él mil años.', 'fire'),
('New', 'Apocalipsis', 20, 7, 'Y cuando los mil años fueren cumplidos, Satanás será suelto de su prisión,', 'fire'),
('New', 'Apocalipsis', 20, 8, 'Y saldrá para engañar las naciones que están sobre los cuatro ángulos de la tierra, á Gog y á Magog, á fin de congregarlos para la batalla; el número de los cuales es como la arena del mar.', 'fire'),
('New', 'Apocalipsis', 20, 9, 'Y subieron sobre la anchura de la tierra, y circundaron el campo de los santos, y la ciudad amada: y de Dios descendió fuego del cielo, y los devoró.', 'fire'),
('New', 'Apocalipsis', 20, 10, 'Y el diablo que los engañaba, fué lanzado en el lago de fuego y azufre, donde está la bestia y el falso profeta; y serán atormentados día y noche para siempre jamás.', 'fire'),
('New', 'Apocalipsis', 20, 11, 'Y vi un gran trono blanco y al que estaba sentado sobre él, de delante del cual huyó la tierra y el cielo; y no fué hallado el lugar de ellos.', 'fire'),
('New', 'Apocalipsis', 20, 12, 'Y vi los muertos, grandes y pequeños, que estaban delante de Dios; y los libros fueron abiertos: y otro libro fué abierto, el cual es de la vida: y fueron juzgados los muertos por las cosas que estaban escritas en los libros, según sus obras.', 'fire'),
('New', 'Apocalipsis', 20, 13, 'Y el mar dió los muertos que estaban en él; y la muerte y el infierno dieron los muertos que estaban en ellos; y fué hecho juicio de cada uno según sus obras.', 'fire'),
('New', 'Apocalipsis', 20, 14, 'Y el infierno y la muerte fueron lanzados en el lago de fuego. Esta es la muerte segunda.', 'fire'),
('New', 'Apocalipsis', 20, 15, 'Y el que no fué hallado escrito en el libro de la vida, fué lanzado en el lago de fuego.', 'fire'),
('New', 'Apocalipsis', 21, 1, 'Y VI un cielo nuevo, y una tierra nueva: porque el primer cielo y la primera tierra se fueron, y el mar ya no es.', 'fire'),
('New', 'Apocalipsis', 21, 2, 'Y yo Juan vi la santa ciudad, Jerusalem nueva, que descendía del cielo, de Dios, dispuesta como una esposa ataviada para su marido.', 'fire'),
('New', 'Apocalipsis', 21, 3, 'Y oí una gran voz del cielo que decía: He aquí el tabernáculo de Dios con los hombres, y morará con ellos; y ellos serán su pueblo, y el mismo Dios será su Dios con ellos.', 'fire'),
('New', 'Apocalipsis', 21, 4, 'Y limpiará Dios toda lágrima de los ojos de ellos; y la muerte no será más; y no habrá más llanto, ni clamor, ni dolor: porque las primeras cosas son pasadas.', 'fire'),
('New', 'Apocalipsis', 21, 5, 'Y el que estaba sentado en el trono dijo: He aquí, yo hago nuevas todas las cosas. Y me dijo: Escribe; porque estas palabras son fieles y verdaderas.', 'fire'),
('New', 'Apocalipsis', 21, 6, 'Y díjome: Hecho es. Yo soy Alpha y Omega, el principio y el fin. Al que tuviere sed, yo le daré de la fuente del agua de vida gratuitamente.', 'fire'),
('New', 'Apocalipsis', 21, 7, 'El que venciere, poseerá todas las cosas; y yo seré su Dios, y él será mi hijo.', 'fire'),
('New', 'Apocalipsis', 21, 8, 'Mas á los temerosos é incrédulos, á los abominables y homicidas, á los fornicarios y hechiceros, y á los idólatras, y á todos los mentirosos, su parte será en el lago ardiendo con fuego y azufre, que es la muerte segunda.', 'fire'),
('New', 'Apocalipsis', 21, 9, 'Y vino á mí uno de los siete ángeles que tenían las siete copas llenas de las siete postreras plagas, y habló conmigo, diciendo: Ven acá, yo te mostraré la esposa, mujer del Cordero.', 'fire'),
('New', 'Apocalipsis', 21, 10, 'Y llevóme en Espíritu á un grande y alto monte, y me mostró la grande ciudad santa de Jerusalem, que descendía del cielo de Dios,', 'fire'),
('New', 'Apocalipsis', 21, 11, 'Teniendo la claridad de Dios: y su luz era semejante á una piedra preciosísima, como piedra de jaspe, resplandeciente como cristal.', 'fire'),
('New', 'Apocalipsis', 21, 12, 'Y tenía un muro grande y alto con doce puertas; y en las puertas, doce ángeles, y nombres escritos, que son los de las doce tribus de los hijos de Israel.', 'fire'),
('New', 'Apocalipsis', 21, 13, 'Al oriente tres puertas; al norte tres puertas; al mediodiá tres puertas; al poniente tres puertas.', 'fire'),
('New', 'Apocalipsis', 21, 14, 'Y el muro de la ciudad tenía doce fundamentos, y en ellos los doce nombres de los doce apóstoles del Cordero.', 'fire'),
('New', 'Apocalipsis', 21, 15, 'Y el que hablaba conmigo, tenía una medida de una caña de oro para medir la ciudad, y sus puertas, y su muro.', 'fire'),
('New', 'Apocalipsis', 21, 16, 'Y la ciudad está situada y puesta en cuadro, y su largura es tanta como su anchura: y él midió la ciudad con la caña, doce mil estadios: la largura y la altura y la anchura de ella son iguales.', 'fire'),
('New', 'Apocalipsis', 21, 17, 'Y midió su muro, ciento cuarenta y cuatro codos, de medida de hombre, la cual es del ángel.', 'fire'),
('New', 'Apocalipsis', 21, 18, 'Y el material de su muro era de jaspe: mas la ciudad era de oro puro, semejante al vidrio limpio.', 'fire'),
('New', 'Apocalipsis', 21, 19, 'Y los fundamentos del muro de la ciudad estaban adornados de toda piedra preciosa. El primer fundamento era jaspe; el segundo, zafiro; el tercero, calcedonia; el cuarto, esmeralda;', 'fire'),
('New', 'Apocalipsis', 21, 20, 'El quinto, sardónica; el sexto, sardio; el séptimo, crisólito; el octavo, berilo; el nono, topacio; el décimo, crisopraso; el undécimo, jacinto; el duodécimo, amatista.', 'fire'),
('New', 'Apocalipsis', 21, 21, 'Y las doce puertas eran doce perlas, en cada una, una; cada puerta era de una perla. Y la plaza de la ciudad era de oro puro como vidrio trasparente.', 'fire'),
('New', 'Apocalipsis', 21, 22, 'Y no vi en ella templo; porque el Señor Dios Todopoderoso es el templo de ella, y el Cordero.', 'fire'),
('New', 'Apocalipsis', 21, 23, 'Y la ciudad no tenía necesidad de sol, ni de luna, para que resplandezcan en ella: porque la claridad de Dios la iluminó, y el Cordero era su lumbrera.', 'fire'),
('New', 'Apocalipsis', 21, 24, 'Y las naciones que hubieren sido salvas andarán en la lumbre de ella: y los reyes de la tierra traerán su gloria y honor á ella', 'fire'),
('New', 'Apocalipsis', 21, 25, 'Y sus puertas nunca serán cerradas de día, porque allí no habrá noche.', 'fire'),
('New', 'Apocalipsis', 21, 26, 'Y llevarán la gloria y la honra de las naciones á ella.', 'fire'),
('New', 'Apocalipsis', 21, 27, 'No entrará en ella ninguna cosa sucia, ó que hace abominación y mentira; sino solamente los que están escritos en el libro de la vida del Cordero.', 'fire'),
('New', 'Apocalipsis', 22, 1, 'DESPUÉS me mostró un río limpio de agua de vida, resplandeciente como cristal, que salía del trono de Dios y del Cordero.', 'fire'),
('New', 'Apocalipsis', 22, 2, 'En el medio de la plaza de ella, y de la una y de la otra parte del río, estaba el árbol de la vida, que lleva doce frutos, dando cada mes su fruto: y las hojas del árbol eran para la sanidad de las naciones.', 'fire'),
('New', 'Apocalipsis', 22, 3, 'Y no habrá más maldición; sino que el trono de Dios y del Cordero estará en ella, y sus siervos le servirán.', 'fire'),
('New', 'Apocalipsis', 22, 4, 'Y verán su cara; y su nombre estará en sus frentes.', 'fire'),
('New', 'Apocalipsis', 22, 5, 'Y allí no habrá más noche; y no tienen necesidad de lumbre de antorcha, ni de lumbre de sol: porque el Señor Dios los alumbrará: y reinarán para siempre jamás.', 'fire'),
('New', 'Apocalipsis', 22, 6, 'Y me dijo: Estas palabras son fieles y verdaderas. Y el Señor Dios de los santos profetas ha enviado su ángel, para mostrar á sus siervos las cosas que es necesario que sean hechas presto.', 'fire'),
('New', 'Apocalipsis', 22, 7, 'Y he aquí, vengo presto. Bienaventurado el que guarda las palabras de la profecía de este libro.', 'fire'),
('New', 'Apocalipsis', 22, 8, 'Yo Juan soy el que ha oído y visto estas cosas. Y después que hube oído y visto, me postré para adorar delante de los pies del ángel que me mostraba estas cosas.', 'fire'),
('New', 'Apocalipsis', 22, 9, 'Y él me dijo: Mira que no lo hagas: porque yo soy siervo contigo, y con tus hermanos los profetas, y con los que guardan las palabras de este libro. Adora á Dios.', 'fire'),
('New', 'Apocalipsis', 22, 10, 'Y me dijo: No selles las palabras de la profecía de este libro; porque el tiempo está cerca.', 'fire'),
('New', 'Apocalipsis', 22, 11, 'El que es injusto, sea injusto todavía: y el que es sucio, ensúciese todavía: y el que es justo, sea todavía justificado: y el santo sea santificado todavía.', 'fire'),
('New', 'Apocalipsis', 22, 12, 'Y he aquí, yo vengo presto, y mi galardón conmigo, para recompensar á cada uno según fuere su obra.', 'fire'),
('New', 'Apocalipsis', 22, 13, 'Yo soy Alpha y Omega, principio y fin, el primero y el postrero.', 'fire'),
('New', 'Apocalipsis', 22, 14, 'Bienaventurados los que guardan sus mandamientos, para que su potencia sea en el árbol de la vida, y que entren por las puertas en la ciudad.', 'fire'),
('New', 'Apocalipsis', 22, 15, 'Mas los perros estarán fuera, y los hechiceros, y los disolutos, y los homicidas, y los idólatras, y cualquiera que ama y hace mentira.', 'fire'),
('New', 'Apocalipsis', 22, 16, 'Yo Jesús he enviado mi ángel para daros testimonio de estas cosas en las iglesias. Yo soy la raíz y el linaje de David, la estrella resplandeciente, y de la mañana.', 'fire'),
('New', 'Apocalipsis', 22, 17, 'Y el Espíritu y la Esposa dicen: Ven. Y el que oye, diga: Ven. Y el que tiene sed, venga: y el que quiere, tome del agua de la vida de balde.', 'fire'),
('New', 'Apocalipsis', 22, 18, 'Porque yo protesto á cualquiera que oye las palabras de la profecía de este libro: Si alguno añadiere á estas cosas, Dios pondrá sobre él las plagas que están escritas en este libro.', 'fire'),
('New', 'Apocalipsis', 22, 19, 'Y si alguno quitare de las palabras del libro de esta profecía, Dios quitará su parte del libro de la vida, y de la santa ciudad, y de las cosas que están escritas en este libro.', 'fire'),
('New', 'Apocalipsis', 22, 20, 'El que da testimonio de estas cosas, dice: Ciertamente, vengo en breve. Amén, sea así. Ven: Señor Jesús.', 'fire'),
('New', 'Apocalipsis', 22, 21, 'La gracia de nuestro Señor Jesucristo sea con todos vosotros. Amén.', 'fire');